### ISSUE TITLE
Continuous popup notification when an incident is published

### ISSUE THREAD

**Issue by aegiap** [sayoun/gandi.widget#33]
When the Gandi platform is under maintenance or an incident is published on http://status.gandi.net the widget show a popup for a second each couple of second with the name of the post on status. In case of a long running maintenance or incident, the notification is quite annoying.

I would like to change the frequency of the popup notification, maybe with a configuration variable. 

Possible solution: if the incident is older than 10 minutes before now, show the popup each 30 seconds with the information for 2 minutes, then decrease the frequency to one popup every hour.

**Comment by sayoun** [comment]
Hello @aegiap , you can configure the frequency of status update in the configuration file of the CLI 
`~/.config/gandi/config.yaml` using the key under widget.status_refresh

**Comment by aegiap** [comment]
@sayoun thank you for the info. Works great. :fireworks:
